// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Get environment variables with fallback for development
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://xanaccmdizurlvjrwizh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhhbmFjY21kaXp1cmx2anJ3aXpoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3NTE4MzUsImV4cCI6MjA2MzMyNzgzNX0.6zZ5TSU7appoIE4_b7ob-dl1zATk3l6L27_SmbfNu2c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);